name: Deployment to QA option3

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select environment to deploy'
        required: true
        type: choice
        default: 'qa'
        options: ['qa', 'prod']
      release_version:
        description: 'Version of the release to deploy'
        required: true
        default: 'latest'

permissions:
  contents: write
  actions: read

jobs:
  Devployment_prep:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: ./terraform
  
  Deployment:
    runs-on: ubuntu-latest
    needs: [Devployment_prep]
    environment: 'prod'
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform

    - name: Terraform Apply
      run: terraform apply -input=false -auto-approve
      working-directory: ./terraform