name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select deployment environment
        required: true
        default: dev-1
        type: choice
        options:
          - dev-1
          - qa1
          - prod
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print GitHub Event
        run: |
          `if [ "${{ github.event_name }}" == "release" ]; then
                echo "Triggered by release, fetching release artifacts for tag: ${{ github.ref }}";
                TAG=$(echo "${{ github.ref }}" | sed 's/^refs\/tags\///');
                echo "TAG1 ${{ TAG }} "
            else
                if [[ "${{ github.ref }}" == refs/tags/* ]]; then
                    echo "Manual release TAG $(echo "${{ github.ref }}" | sed 's/^refs\/tags\///');"
                else
                    echo "${{ github.ref }}";
                fi
            fi`,
