name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select deployment environment
        required: true
        default: dev-1
        type: choice
        options:
          - dev-1
          - qa1
          - prod
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print GitHub Event
        run: |
          echo "Event name ${{ github.event_name }}"
      - name: Print release version
        run: |
          echo "Release version: ${{ github.ref }}"
