name: Example Workflow

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print GitHub Event
        run: |
          echo "Event name ${{ github.event_name }}"
      - name: Print release version
        run: |
          echo "Release version: ${{ github.ref }}"
